name: Bug Report
description: Something is broken
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug. Please fill out the sections below.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you do, and what went wrong?
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Run `klustershield scan ...`
        2. See error
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      placeholder: |
        - OS: Ubuntu 22.04
        - Python: 3.11.x
        - kubernetes client: 35.0.0
        - Cluster: k3s v1.28.4
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Full error output
      render: shell
